name: Bencher Base

on:
  push:
    branches: main

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Build
        run: cargo build
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project hylophile-s-project \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --err \
          --testbed ubuntu-latest \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --adapter rust_criterion "cargo bench"
